/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as LovableSupabaseIntegrationRouteImport } from './routes/lovable.supabase-integration'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableSupabaseIntegrationRoute =
  LovableSupabaseIntegrationRouteImport.update({
    id: '/lovable/supabase-integration',
    path: '/lovable/supabase-integration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lovable/supabase-integration': typeof LovableSupabaseIntegrationRoute
  '/modules/$slug': typeof ModulesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lovable/supabase-integration': typeof LovableSupabaseIntegrationRoute
  '/modules/$slug': typeof ModulesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lovable/supabase-integration': typeof LovableSupabaseIntegrationRoute
  '/modules/$slug': typeof ModulesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resources'
    | '/sitemap.xml'
    | '/lovable/supabase-integration'
    | '/modules/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resources'
    | '/sitemap.xml'
    | '/lovable/supabase-integration'
    | '/modules/$slug'
  id:
    | '__root__'
    | '/'
    | '/resources'
    | '/sitemap.xml'
    | '/lovable/supabase-integration'
    | '/modules/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LovableSupabaseIntegrationRoute: typeof LovableSupabaseIntegrationRoute
  ModulesSlugRoute: typeof ModulesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/supabase-integration': {
      id: '/lovable/supabase-integration'
      path: '/lovable/supabase-integration'
      fullPath: '/lovable/supabase-integration'
      preLoaderRoute: typeof LovableSupabaseIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LovableSupabaseIntegrationRoute: LovableSupabaseIntegrationRoute,
  ModulesSlugRoute: ModulesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
